### ISSUE TITLE
CA credentials do not appear

### ISSUE THREAD

**Issue by stratosgear** [pojntfx/pojde-ng#3]
During the last step of the installation, there is a warning screen suggesting that I press Enter to display the CA certificate and/or QR code, but when I do so, the screen refreshes with a success page but **without** actually showing any CA info...

**Comment by pojntfx** [comment]
Thanks for the bug report @stratosgear! I could actually reproduce that locally; checking now. I'm assuming it's due to me forgetting to backport the architecture identifier from https://github.com/pojntfx/webwormhole-binaries (was i.e. `arm64` before, is `uname -m` now) to here. I'll prepare a PR.

**Comment by pojntfx** [comment]
```bash
pojntfx@8c3c9154628d:/root$ ww
/usr/bin/ww: line 1: Not: command not found
````

Looks like that is indeed the issue -_-

**Comment by stratosgear** [comment]
Cool!  Now how does this propagates to end users? I guess once you push your docker image?

It's not clear, when I should try again, to get the fix! Thanks!

**Comment by pojntfx** [comment]
Yes, exactly! I'll post instructions (basically `pojdectl upgrade -r`) once it has been built. I'm looking at your other issue at the moment (https://github.com/pojntfx/pojde/issues/4) which I think is related to SELinux (I could reproduce it on a clean F34 install, did not occur on F33, where I set SELinux to non-enforcing) :)

**Comment by stratosgear** [comment]
Thanks, but sorry for being stubborn about this.  How will people know that "...once it has been built"? 

I guess I can keep monitoring dockerhub at https://hub.docker.com/r/pojntfx/pojde/tags?page=1&ordering=last_updated for a newer build.

Maybe if you can work a solution with a release number...?  But I know these "administrative" tasks are really boring! Better concentrate on bug fixes first and then improve the infrastructure.  Sorry for bogging you down!

**Comment by pojntfx** [comment]
No problem; pojdectl has CI/CD set up using GitHub actions, so you can monitor the current build process here: https://github.com/pojntfx/pojde/actions/runs/885059787

Once built, you can use `pojdectl apply` again to upgrade: `pojdectl apply my-first-instance 5000 -f -u -r`

I'll be working on the release infrastructure a bit today, you're right, version management and docs surely could see some work. Maybe I'll backport some stuff from https://github.com/pojntfx/bofied 's CI/CD config :)

**Comment by pojntfx** [comment]
Alright, so I've validated that the installation works with the new build on a fresh Debian 10 server on DigitalOcean. https://github.com/pojntfx/pojde/commit/ede7cdd001b3815158225de502a5132d0c23e512 also add support for enforcing SELinux using Podman, although that shouldn't be the problem here. To upgrade, run the following:

```shell
pojdectl upgrade-pojdectl # This will also apply the latest SELinux-related changes to the CLI
pojdectl apply my-first-instance 5000 -f -u -r
```

**Comment by stratosgear** [comment]
Ouch!

```
stratos@hypervasis:~$ pojdectl upgrade-pojdectl
[sudo] password for stratos: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20647  100 20647    0     0   115k      0 --:--:-- --:--:-- --:--:--  115k
/usr/local/bin/pojdectl: line 612: syntax error near unexpected token `)'
/usr/local/bin/pojdectl: line 612: `port} "${host}" "${DOCKER} ps -q -a -f name=${DOCKER_PREFIX}${name}")" ]; then'
```

**Comment by pojntfx** [comment]
Bash will be the bane of my existence xD Sorry, c63911f71df5f3d32a90f98cdfda7bed72aefe0f fixes the issue, as the shell script replaces itself during the upgrade Bash, reads it line-by-line and, after the script has been replaced, reads the wrong lines. Fixed it by using brackets:

```shell
 # Read the following lines into memory first so that replacing the script while it is running doesn't lead to issues    {        # Fetch the latest version from GitHub        sudo curl -L -o /usr/local/bin/pojdectl https://raw.githubusercontent.com/pojntfx/pojde/main/bin/pojdectl
        # Make it executable        sudo chmod +x /usr/local/bin/pojdectl
        # Exit to use the new script        exit    }
```

Updates from here on out should thus not have the issue.

**Comment by stratosgear** [comment]
If you mean that I should just run the upgrade again, now I get:

```
stratos@hypervasis:~$ pojdectl upgrade-pojdectl
[sudo] password for stratos: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20848  100 20848    0     0    97k      0 --:--:-- --:--:-- --:--:--   97k
/usr/local/bin/pojdectl: line 678: ME_NAME}: command not found
Please run "pojdectl apply" again for all instances to re-initialize; if you don't do so, you'll loose secure access to them.
/usr/local/bin/pojdectl: line 681: syntax error near unexpected token `fi'
/usr/local/bin/pojdectl: line 681: `    fi'
```

**Comment by pojntfx** [comment]
No  worries, it has been upgraded, the version you've upgraded from didn't have the upgrade fix :) From the version you have now onwards it should be fixed, i.e. you can re-run the upgrade again now and it should still work.

**Comment by stratosgear** [comment]
Hmm, you are right, rerunning the command does not display any errors now.

But trying to reaplly again with `pojdectl apply inst2 5000` or in a new one with `pojdectl apply inst3 6000` **still** does not show me the QR code, as described in the begining of the thread here...

**Comment by stratosgear** [comment]
Just so you know, I also tried to `pojdectl remove -a` **all** my test instances and tried again with new ones, but still cannot get the CA codes to display!

EDITED: I also did a `pojdectl reset-ca`, too!

**Comment by pojntfx** [comment]
Did you specify the `-u -r -f` flags? u pulls the image, r recreates the container, f skips confirmation prompts. Without them the new image isn't being pulled :)

**Comment by stratosgear** [comment]
Yes, sorry, did not know about these flags. 

So yes, this has been fixed now.  I will be closing the issue!
